### ISSUE TITLE
The script has stopped working as of 5/28/2017.

### ISSUE THREAD

**Issue by drmstwizard** [alexwlchan/finduntaggedtumblrposts.com#13]
The script has stopped working as of 5/28/2017. @alexwlchan

**Comment by alexwlchan** [comment]
Still seems to be working for `example.tumblr.com` and `staff.tumblr.com`, which are the two sites I tend to use for testing. Which Tumblr are you trying to use the site with?

**Comment by drmstwizard** [comment]
aimmyarrowshigh.tumblr.com -- the script page says that it connects to the tumblr, but never loads any posts. The progress counter just stays at 0/[number of posts].

**Comment by alexwlchan** [comment]
I think this was fixed by 27d74be, please reopen if the issue persists.
