### ISSUE TITLE
Not going through all of my posts?

### ISSUE THREAD

**Issue by serp214** [alexwlchan/finduntaggedtumblrposts.com#14]
For some reason, the software keeps stopping once it's gone through 4,220 of my posts. I know that there are more untagged posts going further back than that, but the software is not looking through the other 6,000 posts for some reason.

**Comment by charltus** [comment]
I have the same problem, mine stops at 480 posts when I know I have over 8000.

**Comment by alexwlchan** [comment]
I think this was fixed by 27d74be, please reopen if the issue persists.
